# this file is adapted from:
# https://github.com/joeynmt/joeynmt/blob/master/configs/iwslt14_deen_bpe.yaml

name: "low_resource_example"

data:
    src: "de"
    trg: "en"
    train: "data/train.de-en.tokenized"
    dev:   "data/dev.de-en.tokenized"
    test:  "data/test.de-en.tokenized"
    level: "word"
    lowercase: False
    max_sent_length: 100
    src_vocab: "shared_models/vocab.de-en.txt"
    trg_vocab: "shared_models/vocab.de-en.txt"

testing:
    beam_size: "5"
    alpha: 1.0

training:
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0003
    batch_size: 2048
    batch_type: "token"
    eval_batch_size: 1024
    eval_batch_type: "token"
    scheduling: "plateau"
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 2
    validation_freq: 500
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/low_resource_word2k"
    overwrite: False
    shuffle: True
    use_cuda: False
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]
    label_smoothing: 0.1

model:
    tied_embeddings: True
    tied_softmax: True
    encoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 512
            scale: False
        hidden_size: 512
        bidirectional: True
        dropout: 0.0
        num_layers: 1
    decoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 512
        dropout: 0.0
        hidden_dropout: 0.0
        num_layers: 1
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
